# Generated by Django 5.2.1 on 2025-05-15 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='Тартиб рақами (T/P)')),
                ('name', models.CharField(max_length=255, verbose_name='Баҳолаш мезони')),
                ('name_kaa', models.CharField(max_length=255, null=True, verbose_name='Баҳолаш мезони')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Баҳолаш мезони')),
                ('max_score', models.IntegerField(verbose_name='Максимал балл')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Изоҳ (мезонни баҳолаш учун қўлланма)')),
                ('description_kaa', models.TextField(blank=True, null=True, verbose_name='Изоҳ (мезонни баҳолаш учун қўлланма)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Изоҳ (мезонни баҳолаш учун қўлланма)')),
            ],
            options={
                'verbose_name': 'Баҳолаш мезони',
                'verbose_name_plural': 'Баҳолаш мезонлари',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Йўналиш номи')),
                ('name_kaa', models.CharField(max_length=200, null=True, unique=True, verbose_name='Йўналиш номи')),
                ('name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Йўналиш номи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Қисқача тавсиф')),
                ('description_kaa', models.TextField(blank=True, null=True, verbose_name='Қисқача тавсиф')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Қисқача тавсиф')),
            ],
            options={
                'verbose_name': 'Йўналиш',
                'verbose_name_plural': 'Йўналишлар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JudgeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_direction', models.ForeignKey(blank=True, help_text='Агар йўналиш танланмаса, ҳакам барча йўналишлардаги жамоаларни баҳолай олади.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='judging.direction', verbose_name='Масъул йўналиш (ихтиёрий)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile', to=settings.AUTH_USER_MODEL, verbose_name='Ҳакам (Фойдаланувчи)')),
            ],
            options={
                'verbose_name': 'Ҳакам профили',
                'verbose_name_plural': 'Ҳакам профиллари',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Жамоа номи')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='Тартиб рақами (T/P)')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='judging.direction', verbose_name='Йўналиши')),
            ],
            options={
                'verbose_name': 'Жамоа',
                'verbose_name_plural': 'Жамоалар',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Берилган балл')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('final', 'Қатъий')], default='draft', max_length=10, verbose_name='Ҳолати')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Баҳолаш вақти')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Охирги янгиланиш')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judging.criterion', verbose_name='Мезон')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ҳакам')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judging.team', verbose_name='Жамоа')),
            ],
            options={
                'verbose_name': 'Баҳо',
                'verbose_name_plural': 'Баҳолар',
                'ordering': ['timestamp'],
                'unique_together': {('judge', 'team', 'criterion')},
            },
        ),
    ]
