# Generated by Django 5.2.1 on 2025-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='description_kaa',
            field=models.TextField(blank=True, null=True, verbose_name='Изоҳ (мезонни баҳолаш учун қўлланма)'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Изоҳ (мезонни баҳолаш учун қўлланма)'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='name_kaa',
            field=models.CharField(max_length=255, null=True, verbose_name='Баҳолаш мезони'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Баҳолаш мезони'),
        ),
        migrations.AddField(
            model_name='direction',
            name='description_kaa',
            field=models.TextField(blank=True, null=True, verbose_name='Қисқача тавсиф'),
        ),
        migrations.AddField(
            model_name='direction',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Қисқача тавсиф'),
        ),
        migrations.AddField(
            model_name='direction',
            name='name_kaa',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Йўналиш номи'),
        ),
        migrations.AddField(
            model_name='direction',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Йўналиш номи'),
        ),
    ]
